# SwiftLint Configuration for WingedSwift

# Rules to disable
disabled_rules:
  - line_length
  - trailing_whitespace
  - file_length
  - inclusive_language  # RSS spec uses webMaster tag (industry standard)

# Rules to enable
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - closure_spacing
  - redundant_nil_coalescing
  - first_where
  - sorted_first_last

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - Packages
  - Package.swift

# Rule configurations
identifier_name:
  min_length: 1
  max_length: 60

type_name:
  min_length: 1  # Allow short names for HTML tags (A, P, H1, etc)
  max_length: 50

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

# Custom rules
custom_rules:
  double_space:
    name: "Double space"
    regex: "([a-z,A-Z] \\s+)"
    message: "Double space between words"
    match_kinds: string
