#!/bin/bash
#
# Regenerates the machine-readable tag catalog used by AGENTS.md and the
# .claude/skills/wingedswift skill, straight from the source files, so the two can never drift.
#
# Usage: ./Scripts/generate-tag-catalog.sh
#        ./Scripts/generate-tag-catalog.sh --check   # fail if the checked-in catalog is stale

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCES="$ROOT/Sources/WingedSwift/HTML"
OUTPUT="$ROOT/.claude/skills/wingedswift/references/tag-catalog.md"

emit_group() {
    local folder="$1"
    local title="$2"

    [ -d "$SOURCES/$folder" ] || return 0

    echo ""
    echo "## $title"
    echo ""
    echo "| Element | Swift type | Initializer |"
    echo "| --- | --- | --- |"

    for file in $(ls "$SOURCES/$folder"/*.swift | sort); do
        awk '
            /public class [A-Za-z]+: HTMLTag/ {
                match($0, /public class [A-Za-z]+/)
                type = substr($0, RSTART + 13, RLENGTH - 13)
            }
            /public (convenience )?init\(/ { collecting = 1; signature = "" }
            collecting {
                line = $0
                gsub(/^[ \t]+/, "", line)
                gsub(/[ \t]+$/, "", line)
                signature = (signature == "" ? line : signature " " line)
                if (index($0, ") {") > 0) { collecting = 0; inits[++count] = signature }
            }
            /super\.init\("/ {
                if (tag == "") {
                    match($0, /super\.init\("[a-z0-9]*"/)
                    tag = substr($0, RSTART + 12, RLENGTH - 13)
                }
            }
            END {
                if (type == "") exit
                if (tag == "") tag = "&mdash;"
                for (i = 1; i <= count; i++) {
                    sig = inits[i]
                    sub(/^public convenience init/, type, sig)
                    sub(/^public init/, type, sig)
                    sub(/ \{$/, "", sig)
                    gsub(/\|/, "\\|", sig)
                    printf "| `<%s>` | `%s` | `%s` |\n", tag, type, sig
                }
            }
        ' "$file"
    done
}

generate() {
    cat <<'HEADER'
# WingedSwift tag catalog

Generated by `Scripts/generate-tag-catalog.sh` — do not edit by hand.

Every type below subclasses `HTMLTag`, so every one of them also accepts the chainable helpers
`addClass`, `addClasses`, `setId`, `setStyle`, `setAttribute`, `setRole`, `dataAttribute(s)` and
`ariaAttribute(s)`, each returning `Self`.

Need an element that is not listed? Use `HTMLTag("element-name", attributes:children:content:)`
directly, or `RawHTML("<svg …>")` for markup you already have as a string. Do not invent a type
name — it will not compile.
HEADER

    emit_group "Commons" "Commons"
    emit_group "Tables" "Tables"
    emit_group "Media" "Media"
    emit_group "Forms" "Forms"
    emit_group "Code" "Code"

    cat <<'FOOTER'

## Structural helpers (not in `HTML/`)

| Type | Purpose |
| --- | --- |
| `Fragment` | Renders its children with no wrapper element, keeping pretty-print indentation. |
| `RawHTML` | Emits a markup string verbatim; never escaped. |
| `Attribute` | `Attribute(key:value:escape:)` and `Attribute.boolean("required")`. |
| `HTMLTag` | The base class; use it directly for elements without a dedicated type. |
FOOTER
}

mkdir -p "$(dirname "$OUTPUT")"

if [ "${1:-}" = "--check" ]; then
    if ! diff -q <(generate) "$OUTPUT" > /dev/null 2>&1; then
        echo "❌ tag-catalog.md is out of date. Run ./Scripts/generate-tag-catalog.sh" >&2
        exit 1
    fi
    echo "✅ tag-catalog.md is up to date"
    exit 0
fi

generate > "$OUTPUT"
echo "✅ Wrote $(grep -c '^| \`<' "$OUTPUT") initializers to ${OUTPUT#"$ROOT"/}"
