#!/usr/bin/env python3
"""
Adds a result-builder convenience initializer to every tag type that accepts `children:`.

    Div { H1(content: "Title") }

Swift does not inherit convenience initializers into subclasses that declare their own designated
initializer, so each of the ~70 tag types needs its own. This script writes them from the existing
designated initializer, then the result is reviewed and committed like handwritten code.

Usage: python3 Scripts/generate-builder-inits.py [--check]

`--check` reports which files would change without writing anything.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
HTML = ROOT / "Sources" / "WingedSwift" / "HTML"

INIT_START = re.compile(r"^    public init\($", re.M)
INIT_ONE_LINE = re.compile(r"^    public init\((?P<params>.*)\) \{$", re.M)
CLASS_DECL = re.compile(r"public class (?P<type>\w+): HTMLTag")
TAG_NAME = re.compile(r'super\.init\("(?P<tag>[a-z0-9]*)"')


def split_params(text):
    """Split a parameter list on top-level commas."""
    params, depth, current = [], 0, ""
    for char in text:
        if char in "([":
            depth += 1
        elif char in ")]":
            depth -= 1
        if char == "," and depth == 0:
            params.append(current.strip())
            current = ""
        else:
            current += char
    if current.strip():
        params.append(current.strip())
    return params


def forwarding_argument(param):
    """`for id: String? = nil` -> `for: id`; `_ name: String` -> `name`."""
    declaration = param.split(":")[0].strip()
    names = declaration.split()
    if len(names) == 2:
        external, internal = names
        return internal if external == "_" else f"{external}: {internal}"
    return f"{names[0]}: {names[0]}"


def find_designated_init(source):
    """Return (start, end, params) of the designated initializer, or None."""
    match = INIT_ONE_LINE.search(source)
    if match:
        return match.start(), match.end(), split_params(match.group("params"))

    match = INIT_START.search(source)
    if not match:
        return None
    end = source.index("\n    ) {", match.start()) + len("\n    ) {")
    body = source[match.end():source.index("\n    ) {", match.start())]
    return match.start(), end, split_params(body)


def example_call(type_name, kept):
    """`Div {` or `A(href: "…") {` — only required parameters are shown."""
    required = [p for p in kept if "=" not in p]
    if not required:
        return type_name
    arguments = ", ".join(f"{p.split(':')[0].split()[-1]}: \"…\"" for p in required)
    return f"{type_name}({arguments})"


def builder_init(type_name, tag, params):
    kept = [p for p in params if not p.startswith("children:")]
    signature = ",\n        ".join(kept + ["@HTMLFragmentBuilder children: () -> [HTMLTag]"])
    arguments = ",\n            ".join(
        "children: children()" if p.startswith("children:") else forwarding_argument(p)
        for p in params
    )
    example = example_call(type_name, kept)
    return (
        f"\n\n    /// Initializes a new <{tag}> tag, taking its children from a result builder.\n"
        f"    ///\n"
        f"    /// Identical to the array initializer, with the children written as a trailing\n"
        f"    /// closure — `if`, `for` and `map` are all supported inside it.\n"
        f"    ///\n"
        f"    /// ## Example\n"
        f"    /// ```swift\n"
        f"    /// {example} {{\n"
        f"    ///     P(content: \"Hello\")\n"
        f"    /// }}\n"
        f"    /// ```\n"
        f"    public convenience init(\n"
        f"        {signature}\n"
        f"    ) {{\n"
        f"        self.init(\n"
        f"            {arguments}\n"
        f"        )\n"
        f"    }}"
    )


def builder_test_case(type_name, tag_name, params):
    """One entry of the generated coverage test: `Tag(required…) { P(content: "x") }`."""
    values = {"String": '"x"', "Int": "1", "Double": "1.0", "Bool": "true"}
    required = []
    for param in params:
        if param.startswith("children:") or "=" in param:
            continue
        external = param.split(":")[0].split()[0]
        kind = param.split(":", 1)[1].strip()
        required.append(f"{external}: {values.get(kind, '\"x\"')}")

    call = f"{type_name}({', '.join(required)})" if required else type_name
    return f'        ("{tag_name}", {{ {call} {{ P(content: "x") }} }}),'


def write_builder_tests(cases):
    """Regenerates the suite that calls every builder initializer exactly once."""
    body = "\n".join(cases).rstrip(",")
    (ROOT / "Tests/WingedSwiftTests/BuilderInitCoverageTests.swift").write_text(
        'import Foundation\n'
        'import Testing\n'
        '@testable import WingedSwift\n'
        '\n'
        '// Generated by `Scripts/generate-builder-inits.py` — do not edit by hand.\n'
        '\n'
        "/// Every container's builder initializer must forward its children. These initializers are\n"
        '/// written by a script, so a forwarding mistake in one of seventy files would be silent.\n'
        '@Suite struct BuilderInitCoverageTests {\n'
        '\n'
        '    private static let builders: [(tag: String, make: @Sendable () -> HTMLTag)] = [\n'
        f'{body}\n'
        '    ]\n'
        '\n'
        '    @Test(arguments: builders)\n'
        '    func builderInitializerWrapsItsChildren(_ builder: (tag: String, make: @Sendable () -> HTMLTag)) {\n'
        '        let rendered = builder.make().render()\n'
        '\n'
        '        #expect(rendered.hasPrefix("<\\(builder.tag)"))\n'
        '        #expect(rendered.contains("<p>x</p>"))\n'
        '        #expect(rendered.hasSuffix("</\\(builder.tag)>"))\n'
        '    }\n'
        '}\n'
    )


def main():
    check_only = "--check" in sys.argv
    changed, skipped, cases = [], [], []

    for path in sorted(HTML.rglob("*.swift")):
        source = path.read_text()

        found = find_designated_init(source)
        if not found:
            skipped.append((path.name, "no initializer found"))
            continue

        _, end, params = found
        if not any(p.startswith("children:") for p in params):
            skipped.append((path.name, "no children parameter"))
            continue

        type_match = CLASS_DECL.search(source)
        tag_match = TAG_NAME.search(source)
        if not type_match or not tag_match:
            skipped.append((path.name, "could not read type or tag name"))
            continue

        type_name, tag_name = type_match.group("type"), tag_match.group("tag")
        # Every type that takes children gets a case, whether its initializer is new or not.
        cases.append(builder_test_case(type_name, tag_name, params))

        if "@HTMLFragmentBuilder children" in source:
            continue

        addition = builder_init(type_name, tag_name, params)

        # Insert after the designated initializer's closing brace.
        body_end = source.index("\n    }", end) + len("\n    }")
        updated = source[:body_end] + addition + source[body_end:]

        changed.append(path.name)
        if not check_only:
            path.write_text(updated)

    if not check_only:
        write_builder_tests(cases)

    verb = "would change" if check_only else "updated"
    print(f"{verb}: {len(changed)} initializer(s); {len(cases)} builder test case(s)")
    for name, reason in skipped:
        print(f"  skipped {name}: {reason}")
    return 1 if (check_only and changed) else 0


if __name__ == "__main__":
    sys.exit(main())
