import Foundation
import Testing
@testable import WingedSwift

// Generated by `Scripts/generate-builder-inits.py` — do not edit by hand.

/// Every container's builder initializer must forward its children. These initializers are
/// written by a script, so a forwarding mistake in one of seventy files would be silent.
@Suite struct BuilderInitCoverageTests {

    private static let builders: [(tag: String, make: @Sendable () -> HTMLTag)] = [
        ("code", { Code { P(content: "x") } }),
        ("pre", { Pre { P(content: "x") } }),
        ("a", { A(href: "x") { P(content: "x") } }),
        ("abbr", { Abbr { P(content: "x") } }),
        ("address", { Address { P(content: "x") } }),
        ("article", { Article { P(content: "x") } }),
        ("aside", { Aside { P(content: "x") } }),
        ("blockquote", { Blockquote { P(content: "x") } }),
        ("body", { Body { P(content: "x") } }),
        ("button", { Button { P(content: "x") } }),
        ("canvas", { Canvas { P(content: "x") } }),
        ("cite", { Cite { P(content: "x") } }),
        ("dd", { Dd { P(content: "x") } }),
        ("del", { Del { P(content: "x") } }),
        ("details", { Details { P(content: "x") } }),
        ("dialog", { Dialog { P(content: "x") } }),
        ("div", { Div { P(content: "x") } }),
        ("dl", { Dl { P(content: "x") } }),
        ("dt", { Dt { P(content: "x") } }),
        ("em", { Em { P(content: "x") } }),
        ("figcaption", { Figcaption { P(content: "x") } }),
        ("figure", { Figure { P(content: "x") } }),
        ("footer", { Footer { P(content: "x") } }),
        ("h1", { H1 { P(content: "x") } }),
        ("h2", { H2 { P(content: "x") } }),
        ("h3", { H3 { P(content: "x") } }),
        ("h4", { H4 { P(content: "x") } }),
        ("h5", { H5 { P(content: "x") } }),
        ("h6", { H6 { P(content: "x") } }),
        ("head", { Head { P(content: "x") } }),
        ("header", { Header { P(content: "x") } }),
        ("i", { I { P(content: "x") } }),
        ("ins", { Ins { P(content: "x") } }),
        ("kbd", { Kbd { P(content: "x") } }),
        ("li", { Li { P(content: "x") } }),
        ("main", { MainTag { P(content: "x") } }),
        ("mark", { Mark { P(content: "x") } }),
        ("nav", { Nav { P(content: "x") } }),
        ("noscript", { Noscript { P(content: "x") } }),
        ("ol", { Ol { P(content: "x") } }),
        ("p", { P { P(content: "x") } }),
        ("picture", { Picture { P(content: "x") } }),
        ("q", { Q { P(content: "x") } }),
        ("samp", { Samp { P(content: "x") } }),
        ("section", { Section { P(content: "x") } }),
        ("small", { Small { P(content: "x") } }),
        ("span", { Span { P(content: "x") } }),
        ("strong", { Strong { P(content: "x") } }),
        ("sub", { Sub { P(content: "x") } }),
        ("summary", { Summary { P(content: "x") } }),
        ("sup", { Sup { P(content: "x") } }),
        ("table", { Table { P(content: "x") } }),
        ("td", { Td { P(content: "x") } }),
        ("th", { Th { P(content: "x") } }),
        ("time", { Time { P(content: "x") } }),
        ("tr", { Tr { P(content: "x") } }),
        ("ul", { Ul { P(content: "x") } }),
        ("var", { VarTag { P(content: "x") } }),
        ("datalist", { Datalist { P(content: "x") } }),
        ("fieldset", { Fieldset { P(content: "x") } }),
        ("form", { Form { P(content: "x") } }),
        ("label", { Label { P(content: "x") } }),
        ("legend", { Legend { P(content: "x") } }),
        ("optgroup", { Optgroup(label: "x") { P(content: "x") } }),
        ("output", { Output { P(content: "x") } }),
        ("select", { Select(name: "x") { P(content: "x") } }),
        ("audio", { Audio { P(content: "x") } }),
        ("video", { Video { P(content: "x") } }),
        ("caption", { Caption { P(content: "x") } }),
        ("colgroup", { Colgroup { P(content: "x") } }),
        ("tbody", { Tbody { P(content: "x") } }),
        ("tfoot", { Tfoot { P(content: "x") } }),
        ("thead", { Thead { P(content: "x") } })
    ]

    @Test(arguments: builders)
    func builderInitializerWrapsItsChildren(_ builder: (tag: String, make: @Sendable () -> HTMLTag)) {
        let rendered = builder.make().render()

        #expect(rendered.hasPrefix("<\(builder.tag)"))
        #expect(rendered.contains("<p>x</p>"))
        #expect(rendered.hasSuffix("</\(builder.tag)>"))
    }
}
