name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Swift ${{ matrix.swift-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13]
        swift-version: ['5.9', '5.10']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Swift (Linux)
      if: runner.os == 'Linux'
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift-version }}
    
    - name: Setup Swift (macOS)
      if: runner.os == 'macOS'
      run: |
        # Use system Swift on macOS to avoid Xcode compatibility issues
        swift --version
    
    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v
  
  coverage:
    name: Code Coverage
    runs-on: macos-13
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Swift version
      run: swift --version
    
    - name: Run tests with coverage
      run: swift test --enable-code-coverage
    
    - name: Generate coverage report
      run: |
        xcrun llvm-cov export -format="lcov" \
          .build/debug/WingedSwiftPackageTests.xctest/Contents/MacOS/WingedSwiftPackageTests \
          -instr-profile .build/debug/codecov/default.profdata > coverage.lcov || true
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.lcov
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
      continue-on-error: true
  
  lint:
    name: SwiftLint
    runs-on: macos-13
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: swiftlint lint --strict
      continue-on-error: true
